import type { ExperienceEntry } from '../types/resume';

// Chronological, most recent first. Content migrated verbatim from the
// approved Resume Quest v2 data — no metrics, dollar figures, percentages,
// team sizes, or client names invented.

export const experience: ExperienceEntry[] = [
  {
    id: 'travelers',
    company: 'Travelers Insurance',
    title: 'Sr Developer / Team Lead',
    location: 'Atlanta, GA',
    startDate: 'March 2024',
    achievements: [
      'Building domain APIs using Node.js and API Gateway.',
      'Prototyping AI applications and AI-augmented UI experiences.',
      'Contributing to the codebase and documentation to ensure continuity and code quality.',
      'Participating in design and implementation conversations around deliverables for business stakeholders.',
      'Mentoring developers through code review and pairing, with an emphasis on API contract design.',
      'Partnering with product and business stakeholders to turn ambiguous requirements into scoped, deliverable API work.',
    ],
    technologies: ['Node.js', 'AWS API Gateway', 'TypeScript', 'REST', 'Generative AI prototyping', 'Agile'],
  },
  {
    id: 'cox',
    company: 'Cox Automotive',
    title: 'Sr Developer / Team Lead',
    location: 'Atlanta, GA',
    startDate: 'Jul 2023',
    endDate: 'Mar 2024',
    achievements: [
      'Building RESTful APIs using .NET Core and containers.',
      'Implementing single-spa micro frontends using React.',
      'Leading team discussions on architecture and coding standards.',
      'Containerizing services and standardizing local development so the team could run the stack end to end.',
      'Documenting frontend module boundaries so independently deployed apps could compose without collisions.',
    ],
    technologies: ['.NET Core', 'C#', 'React', 'single-spa', 'Docker', 'REST'],
  },
  {
    id: 'aws',
    company: 'Amazon Web Services',
    title: 'Cloud Application Architect',
    location: 'Atlanta, GA',
    startDate: 'Aug 2021',
    endDate: 'Jun 2023',
    achievements: [
      'Owning end-to-end architecture and development during customer engagements.',
      'Participating in pre-sales meetings and design sessions to fit customer needs.',
      'Meeting with customers to explain AWS offerings in depth and make tailored recommendations for cloud migration and adoption.',
      'Assisting customers during and after migration — lift-and-shift through full rewrites of on-prem architecture.',
      'Building solutions across AWS services: Lambda, API Gateway, S3, Step Functions, DynamoDB, Aurora RDS, and VPC.',
      'Running working sessions and enablement for customer engineering teams so they could operate what we built after handoff.',
      'Translating technical architecture into terms business sponsors could fund and defend.',
    ],
    technologies: [
      'AWS Lambda',
      'API Gateway',
      'S3',
      'Step Functions',
      'DynamoDB',
      'Aurora RDS',
      'VPC',
      'CloudFormation',
      'IaC',
    ],
  },
  {
    id: 'rentready',
    company: 'Rent Ready',
    title: 'Cloud / Dynamics 365 Developer',
    location: 'Charlotte, NC',
    startDate: '2019',
    endDate: 'Aug 2021',
    achievements: [
      'Documenting and developing Azure Functions, web apps, and APIs to extend Dynamics 365 across the organization.',
      'Creating and maintaining plug-ins, workflows, and web resources that drive business processes inside Dynamics 365.',
      'Implementing Service Bus queues to manage messages from Dynamics and trigger downstream Azure Functions.',
      'Creating CI/CD build and release pipelines for Azure Functions, releasing to deployment slots by environment and trigger.',
      "Making architecture decisions in Azure to fit the company's needs — moving apps from dedicated App Service to Consumption, converting apps to Durable Functions, deploying a static Vue.js site to blob storage, and creating non-interactive users in D365.",
      'Creating micro-service applications that act as endpoints or interface with PowerApps and Logic Apps.',
      'Reducing hosting cost by matching each workload to the right Azure compute model instead of a single default.',
    ],
    technologies: [
      'Azure Functions',
      'Durable Functions',
      'Service Bus',
      'Dynamics 365',
      'PowerApps',
      'Logic Apps',
      'Vue.js',
      'Blob Storage',
      'Azure DevOps',
    ],
  },
  {
    id: 'ncourt',
    company: 'nCourt',
    title: 'Mid-Level Web Developer',
    location: 'Kennesaw, GA',
    startDate: '2018',
    endDate: '2019',
    achievements: [
      'Initiated the transition from on-prem TFS version control to Git repositories in Azure DevOps.',
      'Created and maintained frontend applications in Vue.js while building the REST APIs behind them in .NET Core.',
      'Migrated existing stored procedures and database schema to Entity Framework Core using the fluent API.',
      'Created CI/CD build and release pipelines for legacy applications and new development, targeting on-prem or cloud.',
      'Converted local DLLs and libraries into NuGet packages hosted on Azure DevOps.',
      'Migrated legacy applications from VB.NET to C# on .NET Standard, introducing unit testing, regression testing, abstraction, and ORM data access.',
    ],
    technologies: [
      'Vue.js',
      '.NET Core',
      '.NET Standard',
      'Entity Framework Core',
      'Azure DevOps',
      'NuGet',
      'Git',
      'TFS',
    ],
  },
  {
    id: 'atlantic',
    company: 'Atlantic American Corporation',
    title: 'Web Developer',
    location: 'Atlanta, GA',
    startDate: '2015',
    endDate: '2018',
    achievements: [
      'Developed, designed, and published projects to staging and production for public clients and internal users, with 100% on-time delivery.',
      'Created web, console, and REST API applications using .NET Core 2.0 and the .NET Core CLI.',
      'Built single-page applications with the Angular CLI and Webpack, integrating Angular projects into existing MVC 5 applications while preserving CI/CD pipelines.',
      'Collaborated with the CTO and marketing on project parameters and design.',
      'Wrote unit tests to verify expected outcomes, identified bugs in existing code, and implemented enhancements to improve speed and functionality.',
      'Assisted the transition from SVN to a Git-based system in Visual Studio Online, including a CI/CD build and release pipeline.',
      'Maintained and created reports for business users using SSRS and SSIS packages.',
    ],
    technologies: ['.NET Core 2.0', 'Angular', 'Webpack', 'MVC 5', 'SSRS', 'SSIS', 'SVN → Git'],
  },
  {
    id: 'ruralmetro',
    company: 'Rural Metro Ambulance',
    title: 'Critical Care Paramedic',
    location: 'Atlanta, GA',
    startDate: '2009',
    endDate: '2015',
    achievements: [
      'Diagnosed disease processes accurately and efficiently to provide treatment in high-stress settings.',
      'Participated in community education initiatives.',
      'Six years of making irreversible decisions with incomplete information under time pressure — the habit that still shapes how I run an incident or a launch.',
    ],
    technologies: ['Critical care transport', 'Triage', 'Community education', 'Crisis decision-making'],
  },
  {
    id: 'merrill',
    company: 'Merrill Lynch / Princeton Retirement Group',
    title: 'Retirement Resource Representative',
    location: 'Atlanta, GA',
    startDate: '2006',
    endDate: '2009',
    achievements: [
      'Asset retention specialist, with over $25 million retained in 2007.',
      'Co-architect of a Spanish-language voice response system.',
      'Counseled Spanish- and English-speaking participants on fund options, withdrawal procedures, tax consequences, and loan modeling across more than 100 different 401(k) plans, and educated them on plan rules.',
    ],
    technologies: ['Bilingual client service (ES/EN)', 'IVR system design', 'Retirement plan administration'],
  },
];

export const formatDates = (e: ExperienceEntry): string => `${e.startDate} – ${e.endDate ?? 'Present'}`;
